apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-minio
  labels:
    snap.container-tools.io/component: server
spec:
  selector:
    matchLabels:
      snap.container-tools.io/component: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        snap.container-tools.io/component: server
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: snap-minio-pv-claim
      containers:
      - name: minio
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: minio/minio
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: snap-minio-credentials
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: snap-minio-credentials
              key: secret-key
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
