apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snap-minio-pv-claim
  labels:
    snap.container-tools.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
