apiVersion: v1
kind: Service
metadata:
  name: snap-minio-service
  labels:
    snap.container-tools.io/component: server
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    snap.container-tools.io/component: server
